name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Pack
      run: dotnet pack Vortice.Windows.slnx --configuration Release -p:Packing=true

    - name: Test D3D12MemoryAllocator
      run: dotnet test tests/Vortice.D3D12MemoryAllocator.Tests/Vortice.D3D12MemoryAllocator.Tests.csproj --configuration Release

    - name: Publish to NuGet
      if: github.event_name == 'push'
      run: dotnet nuget push artifacts/**/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
